name: use_conda

on: [push, pull_request]

jobs:
  use_conda:
    name: ${{ matrix.os }}_${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python_version: ['3.9']

    steps:
      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: conda_env
          use-only-tar-bz2: true
          python-version: ${{ matrix.python-version }}

      - name: check_info
        shell: bash -el {0}
        run: |
          conda info
          conda list
          which pip
          which python
